logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

server:
  port:
    8088

spring:
  application:
    name: authentication
  datasource:
    driver-class-name: org.h2.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka