logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

server:
  port:
    8088

spring:
  application:
    name: authentication
  datasource:
    driver-class-name: org.h2.Driver
  cloud:
    inetutils:
      ignored-interfaces:
        - eth0
        - eth1
        - eth2
        - eth3
        - lo

eureka:
  client:
    service-url:
      defaultZone: http://${MEGABYTES_LOCAL_URL}:8761/eureka
  instance:
    preferIpAddress: true
    #enabled: false