logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

server:
  port:
    8088

spring:
  application:
    name: authentication


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    #enabled: false